version: '3.9'
services:
  mongo1:
    container_name: mongo1
    image: mongo:latest
    volumes:
      - ./scripts/mongo/rs-init.sh:/scripts/rs-init.sh
      - ./scripts/mongo/init.js:/scripts/init.js
      - ./mongo:/data/db
    networks:
      - api-network
      - mongo-network
    ports:
      - 27017:27017
    depends_on:
      - mongo2
      - mongo3
    links:
      - mongo2
      - mongo3
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs"]


  mongo2:
    container_name: mongo2
    image: mongo:latest
    ports:
      - 27018:27017
    restart: always
    networks:
      - mongo-network
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs"]


  mongo3:
    container_name: mongo3
    image: mongo:latest
    ports:
      - 27019:27017
    restart: always
    networks:
      - mongo-network
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]


volumes:
  mongo: {}


networks:
  mongo-network:
    driver: bridge
  api-network:
    external: true
    name: api-network
