version: '3.9'
services:

  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    env_file:
      - ./api/.env
    volumes:
      - /usr/src/app/node_modules
      - ./api:/usr/src/app
      - ./api/logs:/usr/src/app/logs
    ports:
      - 7750:7743

  nginx:
    container_name: nginx
    image: nginx:latest
    depends_on:
      - api
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/mime.types:/etc/nginx/mime.types

networks:
  default:
    name: api-network
    driver: bridge

