version: '3.9'
services:
  redis-master:
    image: redis:latest
    container_name: redis-master
    networks:
      - api-network
      - redis-network
    volumes:
      - ./redis:/data
    ports:
      - "6379:6379"

  redis-slave1:
    image: redis:latest
    container_name: redis-slave1
    depends_on:
      - redis-master
    networks:
      - redis-network
    command: redis-server --slaveof redis-master 6379
    

  redis-slave2:
    image: redis:latest
    container_name: redis-slave2
    depends_on:
      - redis-master
    networks:
      - redis-network
    command: redis-server --slaveof redis-master 6379
    

networks:
  redis-network:
    driver: bridge
  api-network:
    external: true
    name: api-network
volumes:
  redis: {}